// <auto-generated />
using System;
using HenrymedsReservation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HenrymedsReservation.Migrations
{
    [DbContext(typeof(DB))]
    partial class DBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("HenrymedsReservation.PeriodDB", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("PeriodId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Periods", (string)null);
                });

            modelBuilder.Entity("HenrymedsReservation.SlotDB", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PeriodDBPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ReservationTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("SlotId");

                    b.HasIndex("PeriodDBPeriodId");

                    b.ToTable("Slots", (string)null);
                });

            modelBuilder.Entity("HenrymedsReservation.SlotDB", b =>
                {
                    b.HasOne("HenrymedsReservation.PeriodDB", null)
                        .WithMany("Slots")
                        .HasForeignKey("PeriodDBPeriodId");
                });

            modelBuilder.Entity("HenrymedsReservation.PeriodDB", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
